services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3008:3008"
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/frontend/node_modules
      #- /usr/src/app/backend/node_modules
      
      
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/frontend/node_modules
      # - /usr/src/app/backend/node_modules
      
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/customdb.cnf:/etc/mysql/conf.d/custom.cnf
      - mysql_db_vol:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
  redis:
    image: redis

volumes:
  mysql_db_vol: